name: brianryer
favicon: null
layout_spectrum: 0.53056
typography_spectrum: 0.6935
title: Brian Ryer - Writer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffff'
    - '#12070d'
    - '#715d44'
    - '#b29973'
    - '#74241d'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
